apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-microservice-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: dungvannguyen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-microservice
                port:
                  number: 8080
