apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-microservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-microservice
  template:
    metadata:
      labels:
        app: spring-microservice
    spec:
      containers:
        - name: spring-microservice
          image: registry.gitlab.com/dungnv08111/techcon/web-dungnv:main-bc0fb251-1662257727
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '512Mi'
              cpu: '1'
          volumeMounts:
            - name: log-path
              mountPath: /var/log/app
          ports:
            - name: http
              containerPort: 8080
#          readinessProbe:
#            httpGet:
#              path: /demo/status
#              port: http
#            initialDelaySeconds: 20
#            periodSeconds: 15
#            failureThreshold: 6
#          livenessProbe:
#            httpGet:
#              path: /demo/status
#              port: http
#            initialDelaySeconds: 120
      volumes:
        - name: log-path
          hostPath:
            path: /var/log/app
      imagePullSecrets:
        - name: docker-repos.registry.gitlab.com-secret