---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: grafana-pvc
    app.kubernetes.io/instance: grafana-pvc
    app.kubernetes.io/managed-by: none
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-pv
