---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: alertmanager-config
    app.kubernetes.io/instance: alertmanager-config
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/part-of: monitoring-stack
    app.kubernetes.io/managed-by: none
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: >
    global:
      resolve_timeout: 1m

    route:
      # default route, if no matcher matches the given alert
      receiver: 'slack-notifications'

      routes:
        - match_re:
            severity: warning|error
            alertname: xxxxxx_(.+)
          receiver: slack-notifications

    receivers:
      - name: 'slack-notifications'
        slack_configs:
        - api_url: 'https://hooks.slack.com/services/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'
          channel: '#techcon'
          send_resolved: true
          icon_url: https://avatars3.githubusercontent.com/u/3380462
          title: |-
           [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
           {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
             {{" "}}(
             {{- with .CommonLabels.Remove .GroupLabels.Names }}
               {{- range $index, $label := .SortedPairs -}}
                 {{ if $index }}, {{ end }}
                 {{- $label.Name }}="{{ $label.Value -}}"
               {{- end }}
             {{- end -}}
             )
           {{- end }}
          text: >-
           {{ range .Alerts -}}
           *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

           *Description:* {{ .Annotations.description }}

           *Details:*
             {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
             {{ end }}
           {{ end }}
