---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: alertmanager-config
    app.kubernetes.io/instance: alertmanager-config
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/part-of: monitoring-stack
    app.kubernetes.io/managed-by: none
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: >
    global:
      resolve_timeout: 1m

    route:
      # default route, if no matcher matches the given alert
      receiver: 'dungnv.itdn'

      routes:
        - match_re:
            severity: warning|error
            alertname: xxxxxx_(.+)
          receiver: dungnv.itdn

    receivers:
      - name: 'dungnv.itdn'
        email_configs:
          - to: 'helloworld.itdn@gmail.com'
            from: 'dungnv.itdn@gmail.com'
            send_resolved: true
            smarthost: 'smtp.gmail.com:587'
            auth_username: 'dungnv.itdn@gmail.com'
            auth_password: 'jifmjanjgdsfnwgc'
            require_tls: true
            tls_config:
              insecure_skip_verify: true
