---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: alertmanager-config
    app.kubernetes.io/instance: alertmanager-config
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/part-of: monitoring-stack
    app.kubernetes.io/managed-by: none
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: >
    global:
      resolve_timeout: 1m

    route:
      # default route, if no matcher matches the given alert
      receiver: 'slack-notifications'

      routes:
        - match_re:
            severity: warning|error
            alertname: xxxxxx_(.+)
          receiver: slack-notifications

    receivers:
      - name: 'slack-notifications'
        slack_configs:
        - api_url: 'https://hooks.slack.com/services/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'
          channel: '#techcon'
          send_resolved: true
