---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: prometheus-data-pvc
    app.kubernetes.io/instance: prometheus-data-pvc
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring-stack
    app.kubernetes.io/managed-by: none
  name: prometheus-data-pvc
  namespace: techcon-monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-data-pv
