apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app
  namespace: default
spec:
  dnsNames:
    - thuyenthunghoian.com
  secretName: letsencrypt-secret-dvnguyen
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer